stages:
  - test
  - build

default:
  image: "node:16.13.2-alpine"
  before-script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile --no-progress
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .yarn-cache

test:
  stage: test
  script:
    - yarn build

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
